export const CONVERSION_TYPES = {
  'pdf-to-word': {
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    inputFormats: ['.pdf'],
    outputFormat: '.docx',
    icon: 'pdf',
    category: 'document',
    maxSize: 50 * 1024 * 1024,
  },
  'word-to-pdf': {
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    inputFormats: ['.doc', '.docx'],
    outputFormat: '.pdf',
    icon: 'word',
    category: 'document',
    maxSize: 50 * 1024 * 1024,
  },
  'pdf-to-image': {
    name: 'PDF to Image',
    description: 'Convert PDF pages to PNG or JPG images',
    inputFormats: ['.pdf'],
    outputFormat: '.png',
    icon: 'pdf',
    category: 'document',
    maxSize: 50 * 1024 * 1024,
  },
  'image-to-pdf': {
    name: 'Image to PDF',
    description: 'Convert images to PDF documents',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp'],
    outputFormat: '.pdf',
    icon: 'image',
    category: 'image',
    maxSize: 25 * 1024 * 1024,
  },
  'word-to-image': {
    name: 'Word to Image',
    description: 'Convert Word documents to images',
    inputFormats: ['.doc', '.docx'],
    outputFormat: '.png',
    icon: 'word',
    category: 'document',
    maxSize: 50 * 1024 * 1024,
  },
  'image-to-word': {
    name: 'Image to Word',
    description: 'Extract text from images using OCR and create Word documents',
    inputFormats: ['.png', '.jpg', '.jpeg'],
    outputFormat: '.docx',
    icon: 'image',
    category: 'image',
    maxSize: 25 * 1024 * 1024,
  },
  'excel-to-pdf': {
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    inputFormats: ['.xlsx', '.xls'],
    outputFormat: '.pdf',
    icon: 'excel',
    category: 'spreadsheet',
    maxSize: 50 * 1024 * 1024,
  },
  'pdf-to-excel': {
    name: 'PDF to Excel',
    description: 'Convert PDF tables to Excel spreadsheets',
    inputFormats: ['.pdf'],
    outputFormat: '.xlsx',
    icon: 'pdf',
    category: 'spreadsheet',
    maxSize: 50 * 1024 * 1024,
  },
  'ppt-to-pdf': {
    name: 'PowerPoint to PDF',
    description: 'Convert presentations to PDF',
    inputFormats: ['.pptx', '.ppt'],
    outputFormat: '.pdf',
    icon: 'ppt',
    category: 'presentation',
    maxSize: 100 * 1024 * 1024,
  },
  'pdf-to-ppt': {
    name: 'PDF to PowerPoint',
    description: 'Convert PDF to editable presentations',
    inputFormats: ['.pdf'],
    outputFormat: '.pptx',
    icon: 'pdf',
    category: 'presentation',
    maxSize: 50 * 1024 * 1024,
  },
  'merge-pdf': {
    name: 'Merge PDFs',
    description: 'Combine multiple PDF files into one',
    inputFormats: ['.pdf'],
    outputFormat: '.pdf',
    icon: 'pdf',
    category: 'pdf-tools',
    maxSize: 100 * 1024 * 1024,
    multiFile: true,
  },
  'split-pdf': {
    name: 'Split PDF',
    description: 'Split a PDF into separate pages or ranges',
    inputFormats: ['.pdf'],
    outputFormat: '.zip',
    icon: 'pdf',
    category: 'pdf-tools',
    maxSize: 100 * 1024 * 1024,
  },
  'compress-pdf': {
    name: 'Compress PDF',
    description: 'Reduce PDF file size',
    inputFormats: ['.pdf'],
    outputFormat: '.pdf',
    icon: 'pdf',
    category: 'pdf-tools',
    maxSize: 100 * 1024 * 1024,
  },
  'image-compress': {
    name: 'Compress Image',
    description: 'Reduce image file size while maintaining quality',
    inputFormats: ['.png', '.jpg', '.jpeg', '.webp'],
    outputFormat: '.jpg',
    icon: 'image',
    category: 'image',
    maxSize: 25 * 1024 * 1024,
  },
  'word-to-html': {
    name: 'Word to HTML',
    description: 'Convert Word documents to HTML',
    inputFormats: ['.docx'],
    outputFormat: '.html',
    icon: 'word',
    category: 'document',
    maxSize: 50 * 1024 * 1024,
  },
  'html-to-pdf': {
    name: 'HTML to PDF',
    description: 'Convert HTML files to PDF',
    inputFormats: ['.html', '.htm'],
    outputFormat: '.pdf',
    icon: 'html',
    category: 'document',
    maxSize: 10 * 1024 * 1024,
  },
  'csv-to-excel': {
    name: 'CSV to Excel',
    description: 'Convert CSV files to Excel spreadsheets',
    inputFormats: ['.csv'],
    outputFormat: '.xlsx',
    icon: 'csv',
    category: 'spreadsheet',
    maxSize: 25 * 1024 * 1024,
  },
  'excel-to-csv': {
    name: 'Excel to CSV',
    description: 'Convert Excel spreadsheets to CSV',
    inputFormats: ['.xlsx', '.xls'],
    outputFormat: '.csv',
    icon: 'excel',
    category: 'spreadsheet',
    maxSize: 25 * 1024 * 1024,
  },
};

export const CATEGORIES = {
  document: { name: 'Documents', icon: 'doc' },
  image: { name: 'Images', icon: 'img' },
  spreadsheet: { name: 'Spreadsheets', icon: 'xls' },
  presentation: { name: 'Presentations', icon: 'ppt' },
  'pdf-tools': { name: 'PDF Tools', icon: 'pdf' },
};

export const getConversionType = (type) => CONVERSION_TYPES[type] || null;
export const getAllTypes = () => Object.entries(CONVERSION_TYPES);
export const getTypesByCategory = (category) =>
  Object.entries(CONVERSION_TYPES).filter(([, v]) => v.category === category);
